"""
harness/docs_builder.py
-----------------------
Regenerates docs/index.md (the GitHub Pages landing page) from the
findings JSONL index after each run cycle.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import List, Dict, Any

import yaml

logger = logging.getLogger(__name__)

VERDICT_ICON = {
    "exploited": "🔴",
    "suspicious": "🟠",
    "benign": "✅",
    "inconclusive": "⚪",
}


def load_findings_index(jsonl_path: str) -> List[Dict[str, Any]]:
    """Load all findings from the JSONL index file."""
    path = Path(jsonl_path)
    if not path.exists():
        return []
    findings = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    findings.append(json.loads(line))
                except json.JSONDecodeError:
                    logger.warning("Skipping malformed JSONL line: %s", line[:80])
    return findings


def build_index(
    jsonl_path: str,
    docs_dir: str = "./docs",
    site_title: str = "OpenClaw Findings",
) -> Path:
    """
    Rebuild docs/index.md from the findings JSONL index.
    Returns path to the written index file.
    """
    findings = load_findings_index(jsonl_path)
    docs_path = Path(docs_dir)
    docs_path.mkdir(parents=True, exist_ok=True)

    # Sort newest first
    findings_sorted = sorted(
        findings,
        key=lambda f: f.get("investigated_at", ""),
        reverse=True,
    )

    lines = [
        "---",
        f'title: "{site_title}"',
        "layout: default",
        "---",
        "",
        f"# {site_title}",
        "",
        "> Automated vulnerability exploitation investigation reports generated by **OpenClaw**.",
        "",
        "---",
        "",
    ]

    if not findings_sorted:
        lines += [
            "## No findings yet",
            "",
            "Run the harness to generate investigation reports:",
            "```bash",
            "python -m harness.orchestrator --raw-telemetry local",
            "```",
        ]
    else:
        # Summary stats
        verdicts = [f.get("tier1", {}).get("verdict", "inconclusive") for f in findings_sorted]
        exploited = verdicts.count("exploited")
        suspicious = verdicts.count("suspicious")
        benign = verdicts.count("benign")
        inconclusive = verdicts.count("inconclusive")

        lines += [
            "## Summary",
            "",
            f"| 🔴 Exploited | 🟠 Suspicious | ✅ Benign | ⚪ Inconclusive | Total |",
            f"|---|---|---|---|---|",
            f"| {exploited} | {suspicious} | {benign} | {inconclusive} | {len(findings_sorted)} |",
            "",
            "---",
            "",
            "## All Findings",
            "",
            "| CVE | Run | Verdict | Workloads | Date | Telemetry |",
            "|---|---|---|---|---|---|",
        ]

        for f in findings_sorted:
            run_id = f.get("run_id", "?")
            cve_id = f.get("cve_id", "?")
            verdict = f.get("tier1", {}).get("verdict", "inconclusive")
            icon = VERDICT_ICON.get(verdict, "⚪")
            workloads = f.get("workloads_investigated", [])
            wl_str = ", ".join(workloads[:3])
            if len(workloads) > 3:
                wl_str += f" +{len(workloads)-3} more"
            date = f.get("investigated_at", "?")[:10]
            source = f.get("raw_telemetry_source", "?")
            slug = f"{cve_id}_{run_id[:8]}"
            lines.append(
                f"| [{cve_id}](./{slug}.html) "
                f"| `{run_id[:8]}` "
                f"| {icon} {verdict.upper()} "
                f"| {wl_str} "
                f"| {date} "
                f"| `{source}` |"
            )

    index_path = docs_path / "index.md"
    index_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Rebuilt docs/index.md with %d findings", len(findings_sorted))

    # Also write _data/findings_index.yaml for Jekyll data access
    data_dir = docs_path / "_data"
    data_dir.mkdir(exist_ok=True)
    with open(data_dir / "findings_index.yaml", "w") as f:
        yaml.dump(
            {"findings": findings_sorted},
            f, default_flow_style=False, sort_keys=False, allow_unicode=True
        )

    return index_path
